Merged develop into master
* TRANSLATE-3206 Start work on DateProtection

* TRANSLATE-3206 Finish DateProtection

* TRANSLATE-3206 Add ChunkProtection service, compose NumberProtection, add tests

* TRANSLATE-3206 Fix test

* TRANSLATE-3206 Additional fixes:
    - add new date format
    - redo number protection to iterable
    - create whitespace protector
    - add tests

* https://jira.translate5.net/browse/TRANSLATE-3408
    Implement proper segmentation for InstantTranslate

    1.func.php:i($value): var_dump() is used if $value is null
    2.editor_Plugins_Okapi_Bconf_Segmentation_Srx
     - added
       - getSegmentationRules(string $rfc5646)
       - splitTextToSegments(string $text, array $rules)
       - disableCapturingGroups(string $regex)
    3.added formatting/indentation for
     - application/modules/editor/Plugins/Okapi/data/srx/translate5/languages-(1|2).srx

* https://jira.translate5.net/browse/TRANSLATE-3408
    Implement proper segmentation for InstantTranslate

    editor_Plugins_Okapi_Bconf_Segmentation_Srx
     - cosmetic changes
       - comments improved
       - renamed {separator => delimiter}

* https://jira.translate5.net/browse/TRANSLATE-3408
    Implement proper segmentation for InstantTranslate

    added:
     - Translate3408Test.php
     - Translate3408Test/segmented.json

* TRANSLATE-3206 Refactoring:
    - Extract AbstractProtector
    - Add usage of IntlDateFormatter to format default dates
    - Adjust tests

* TRANSLATE-3206 Create FloatProtctor

* TRANSLATE-3206 Add test case

* Merged master into develop

    * TRANSLATE-3441 Translate5 UI errors
         - Cannot read properties of undefined (reading 'get') -> g.cache (MatchGridViewController.js:134:33)

    * - this.getCommentList() is undefined -> handleCommentChange (CommentNavigation.js:58:50)

    * TRANSLATE-3432: Logger to catch more info about no access exception
         - log user info in addition

    * TRANSLATE-3441 Translate5 UI errors
         - Editor.data.task.load is not a function -> MultiUserUsage.js:574:30

    * TRANSLATE-3422 Language mapping does not work correctly for TBX, that are imported in a zip

    * TRANSLATE-3432: Logger to catch more info about no access exception
         - remove user log

    * TRANSLATE-3442-fix-client-pm
        * FIX: the customer-store needs to be loaded even when customer-management is invisible for certain otehr management-views/actions
        * FIX: a client-pm should not be able to change his own subroles

    * doc

    * doc

    * TRANSLATE-3441 Translate5 UI errors
         - undefined is not an object (evaluating 'e.preventDefault') : goToUpperByWorkflowNoSave -> Editor.js:868:10

    * submodules updated

    * change log and submodules release translate5 - 6.5.1

* https://jira.translate5.net/browse/TRANSLATE-3408
    Implement proper segmentation for InstantTranslate

    reverted Okapi/data/srx/translate5/languages-(1|2).srx
    as advised by Axel in comment for PR https://bitbucket.org/mittagqi/translate5/pull-requests/900

* https://jira.translate5.net/browse/TRANSLATE-3408
    Implement proper segmentation for InstantTranslate

    changes according to Axel's comments on PR https://bitbucket.org/mittagqi/translate5/pull-requests/900/
    1.Translate3408Test: rewritten to be Unit-test rather than Api-test
    2.editor_Plugins_Okapi_Bconf_Segmentation_Srx
     - added const SYSTEM_TARGET_SRX = '...../languages-2.srx'
     - added public static createSystemTargetSrx()
       - new self() returned with usage of self::SYSTEM_TARGE_SRX as 1st arg

* https://jira.translate5.net/browse/TRANSLATE-3408
    Implement proper segmentation for InstantTranslate

    Translate3408Test->testSegmentation(): small improvement

* TRANSLATE-3206 Update FloatProtctor

* TRANSLATE-3206 Simplify float protector joined regex

* TRANSLATE-3206 Create IntegerProtector

* Moving Segmentation-Test to Okapi-folder where it belongs ...

* - google translate tests

* reset mistankenly added changes due to wrong target branch

* TRANSLATE-3206 Fix encoding in TagProtection

* TRANSLATE-3206 Implement LanguageNumberFormatRepository. Add migration

* TRANSLATE-3206 Create LanguageRepository

* TRANSLATE-3206 Implement number protection with tags

* TRANSLATE-3206 Protect html entities on handling

* TRANSLATE-3206 Place ext-intl requrement in ext section

* TRANSLATE-3206 Clean up

* TRANSLATE-3206-Add-convert-to-internal-tags-logic

* TRANSLATE-3206 Move tags to tags folder

* TRANSLATE-3206-Protect-numbers-and-whitespaces-on-import

* TRANSLATE-3206 Render number tags in editor

* Merge pull request #925 in mittagqi/translate5 from hotfix/fix-token-visibility to develop

    Hide token in PUT action

    * Hide token in PUT action

    Approved by Thomas Lauria

* Merge pull request #909 in mittagqi/translate5 from bugfix/TRANSLATE-3447-commenting-on-segment to develop

    TRANSLATE-3447: Commenting on segment possible for read-only task

    * TRANSLATE-3447: Commenting on segment possible for read-only task

    Approved by Axel Becher
    Approved by Thomas Lauria

* Revert "Merged in feature/TRANSLATE-3206-Render-number-tags-in-editor (pull request #915)"

    This reverts commit 003f1130b2615a3ec6dd9a5971b6b997c3811e14, reversing
    changes made to ac1508d9de52247080b3ee48bcaf57ed5b244ed8.

* Merged master into develop

    * submodules updated

    * change log and submodules release translate5 - 6.5.2

* Merge pull request #944 in mittagqi/translate5 from bugfix/TRANSLATE-3477-acl-cleanup to develop

    Bugfix/TRANSLATE-3477 acl cleanup

    * TRANSLATE-3477: Add missing ACL right and role documentation
    - add task types
    - finalize role:lost command
    * TRANSLATE-3477: Add missing ACL right and role documentation
    - more resources classified
    - removed old Resources class
    * TRANSLATE-3477: Add missing ACL right and role documentation
    - convert to namespaces
    * TRANSLATE-3477: Add missing ACL right and role documentation
    - editor ACL rights
    - separated some into the corresponding plugins
    - introduced Resource classes which provides information about their containing ACL rights
    - renamed Access to Acl
    * TRANSLATE-3477: Add missing ACL right and role documentation
    - convert initial resources
    - convert first bunch of roles

    Approved by Aleksandar Mitrev
    Approved by Axel Becher

* Merge pull request #918 in mittagqi/translate5 from feature/TRANSLATE-3403-show-history-of-term-or-a to develop

    Feature/TRANSLATE-3403 show history of term or a

    * Merged develop into feature/TRANSLATE-3403-show-history-of-term-or-a
    * https://jira.translate5.net/browse/TRANSLATE-3403
    Show history of term or attribute in TermPortal

    added support for cases when `updatedBy` is NULL in history-record and/or in term/attribute-record
     - editor_Models_Term_History->getByTermId()
     - editor_Models_Term_AttributeHistory->getByAttrId()
    * https://jira.translate5.net/browse/TRANSLATE-3403
    Show history of term or attribute in TermPortal

    1.Editor_Bootstrap->_initRestRoutes(): added 'editor/term/:id/history'-route
    2.editor_Models_Term_AttributeHistory->getByAttrId()
     - `type` is added to SELECT
     - attribute's current state is prepended as the most recent history-record
    3.added
     - editor_Models_Term_History->getByTermId(int $termId): array
     - TermController->historyAction()
    * https://jira.translate5.net/browse/TRANSLATE-3403
    Show history of term or attribute in TermPortal

    1.Editor_Bootstrap->_initRestRoutes(): added 'editor/attribute/:id/history'-route
    2.added AttributeController->historyAction()
    3.added editor_Models_Term_AttributeHistory->getByAttrId(int $attrId, ?string $mainLang = null): array

    Approved by Aleksandar Mitrev

* Merge pull request #930 in mittagqi/translate5 from feature/TRANSLATE-1436-add-or-propose-terminolog to develop

    https://jira.translate5.net/browse/TRANSLATE-1436 Add or propose terminology directly from translate5 task

    * https://jira.translate5.net/browse/TRANSLATE-1436
    Add or propose terminology directly from translate5 task

    changes according to Leon's comments on PR https://bitbucket.org/mittagqi/translate5/pull-requests/930
     - renamed TermModel::{allowedProcessStatuses => getAllowedProcessStatuses}() in definition and usages:
      - (Term|Attribute)Controller
    * https://jira.translate5.net/browse/TRANSLATE-1436
    Add or propose terminology directly from translate5 task

    editor_Models_Terminology_Models_TermModel
     - searchTermEntryIdsBy(..., string $term)
       - added trim() for $term-arg invocation
    * Merged develop into feature/TRANSLATE-1436-add-or-propose-terminolog
    * https://jira.translate5.net/browse/TRANSLATE-1436
    Add or propose terminology directly from translate5 task

    TermController
     - added minor changes in comments and wordings
    * https://jira.translate5.net/browse/TRANSLATE-1436
    Add or propose terminology directly from translate5 task

    1.AttributeController
     - changed everythere
       - editor_Models_Terminology_Models_AttributeModel to AttributeModel::class
       - editor_Models_Terminology_Models_TermModel to TermModel::class
       - use editor_Models_TermCollection_TermCollection to TermCollection::class
     - _attrupdateCheckProcessStatusChangeIsAllowed()
       - moved certain code to TermModel::allowedProcessStatuses()
    2.TermController
     - changed everythere
       - editor_Models_Terminology_Models_TermModel to TermModel::class
     - postAction():
       - processStatus-param and sourceProcessStatus-param are now respected if given
       - added jflush-msg if checkExisting-param is given
     - _postCheckParams()
       - added jcheck-rules for processStatus and sourceProcessStatus params
         - with TermModel::allowedProcessStatuses() usage
       - special is now invoked if checkExisting-param is given
         - source or target term is attached to target or source if exists
    	 - failure flushed if both exists under same termEntryId
    	 - both saved under new termEntryId if not exist
    3.editor_Models_Terminology_Models_TermModel
     - added searchTermEntryIdsBy(int $collectionId, string $language, string $term)
     - added static allowedProcessStatuses(string $current = 'unprocessed', bool $includeCurrent = true)
    * https://jira.translate5.net/browse/TRANSLATE-1436
    Add or propose terminology directly from translate5 task

    1.public/css/translate5.css
     - added styles for usage source/target fields' triggers as language flags
       in segment editor's terminology proposal dialog
    2.js/app/store/admin/Languages.js
     - added iso3166Part1alpha2 to the list of store's fields
    * https://jira.translate5.net/browse/TRANSLATE-1436
    Add or propose terminology directly from translate5 task

    grid/ToolbarViewModel.js: added data.proposeTerminologyButtonActive: false

    Approved by Leon Kyz
    Approved by Thomas Lauria

* TRANSLATE-3477: Add missing ACL right and role documentation
    - fix SQL order

* Merged master into develop

    * TRANSLATE-3487 Fix tags replacement

    * TRANSLATE-3487 Fix updating target

    * TRANSLATE-3487 Fix regexp in tag-check

    * manual release notes 6.5.4

    * manual release notes 6.5.4

    * TRANSLATE-3487 Fix regexp in tag-check

    * submodules updated

    * change log and submodules release translate5 - 6.5.5

* Log if a password reset was requested!