Merged master into develop
* TRANSLATE-3441 Translate5 UI errors
     - Cannot read properties of undefined (reading 'get') -> g.cache (MatchGridViewController.js:134:33)

* - this.getCommentList() is undefined -> handleCommentChange (CommentNavigation.js:58:50)

* TRANSLATE-3432: Logger to catch more info about no access exception
     - log user info in addition

* TRANSLATE-3441 Translate5 UI errors
     - Editor.data.task.load is not a function -> MultiUserUsage.js:574:30

* TRANSLATE-3422 Language mapping does not work correctly for TBX, that are imported in a zip

* TRANSLATE-3432: Logger to catch more info about no access exception
     - remove user log

* TRANSLATE-3442-fix-client-pm
    * FIX: the customer-store needs to be loaded even when customer-management is invisible for certain otehr management-views/actions
    * FIX: a client-pm should not be able to change his own subroles

* doc

* doc

* TRANSLATE-3441 Translate5 UI errors
     - undefined is not an object (evaluating 'e.preventDefault') : goToUpperByWorkflowNoSave -> Editor.js:868:10

* submodules updated

* change log and submodules release translate5 - 6.5.1